name: Shopify to Google Sheets Sync

on:
  # Run every 2 hours
  schedule:
    - cron: '0 */2 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create config file from secrets
      run: |
        cat > config.json << EOF
        {
          "shopify_store_name": "${{ secrets.SHOPIFY_STORE_NAME }}",
          "shopify_access_token": "${{ secrets.SHOPIFY_ACCESS_TOKEN }}",
          "google_service_account_file": "service_account.json",
          "template_spreadsheet": "Customer Orders",
          "target_spreadsheet": "${{ secrets.TARGET_SPREADSHEET }}",
          "lookback_days": 5,
          "batch_size": 250,
          "max_retries": 3,
          "retry_delay": 5,
          "db_path": "shopify_sync.db"
        }
        EOF
        
    - name: Create Google service account file
      run: |
        echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}' > service_account.json
        
    - name: Debug config (remove after testing)
      run: |
        echo "=== Config file check ==="
        python -c "import json; c=json.load(open('config.json')); print('Token length:', len(c.get('shopify_access_token',''))); print('First 10:', c.get('shopify_access_token','')[:10])"
        
    - name: Run sync validation
      run: |
        python test_setup.py
        
    - name: Run Shopify sync
      run: |
        python shopify_sheets_sync.py
        
    - name: Show sync status
      run: |
        python sync_manager.py status
        
    - name: Check for errors
      run: |
        python sync_manager.py errors
        
    - name: Upload logs as artifacts (on failure)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: sync-logs
        path: |
          shopify_sync.log
          shopify_sync.db
        retention-days: 7