name: Shopify to Google Sheets Sync

on:
  # Run every 2 hours
  schedule:
    - cron: '0 */2 * * *'
  
  # Allow manual triggering
  workflow_dispatch:

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Create config file from secrets
      run: |
        cat > config.json << EOF
        {
          "shopify_store_name": "${{ secrets.SHOPIFY_STORE_NAME }}",
          "shopify_access_token": "${{ secrets.SHOPIFY_ACCESS_TOKEN }}",
          "google_service_account_file": "service_account.json",
          "template_spreadsheet": "Customer Orders",
          "target_spreadsheet": "${{ secrets.TARGET_SPREADSHEET }}",
          "lookback_days": 5,
          "batch_size": 250,
          "max_retries": 3,
          "retry_delay": 5,
          "db_path": "shopify_sync.db"
        }
        EOF
        
    - name: Debug config file (remove after testing)
      run: |
        echo "=== Raw config.json file ==="
        cat config.json
        echo ""
        echo "=== Token validation ==="
        python -c "import json; config=json.load(open('config.json')); token=config.get('shopify_access_token',''); print('Token length:', len(token)); print('Starts with shpat_:', token.startswith('shpat_')); print('First 10 chars:', token[:10])"
        
    - name: Create Google service account file
      run: |
        echo '${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON }}' > service_account.json
        
    - name: Check secrets are available
      run: |
        echo "Checking GitHub Secrets availability..."
        echo "SHOPIFY_STORE_NAME: ${{ secrets.SHOPIFY_STORE_NAME != '' }}"
        echo "SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN != '' }}"
        echo "TARGET_SPREADSHEET: ${{ secrets.TARGET_SPREADSHEET != '' }}"
        echo "GOOGLE_SERVICE_ACCOUNT_JSON: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_JSON != '' }}"
        
    - name: Verify config file content
      run: |
        echo "=== Full config.json content (JSON structure check) ==="
        cat config.json
        echo ""
        echo "=== Python JSON validation ==="
        python -c "
import json
try:
    with open('config.json', 'r') as f:
        config = json.load(f)
    print('✓ JSON is valid')
    print(f'✓ Keys found: {list(config.keys())}')
    
    # Check each required field
    required = ['shopify_store_name', 'shopify_access_token', 'target_spreadsheet']
    for key in required:
        if key in config and config[key]:
            print(f'✓ {key}: present and not empty')
        else:
            print(f'✗ {key}: missing or empty')
            print(f'  Value: \"{config.get(key, \"NOT_FOUND\")}\"')
except Exception as e:
    print(f'✗ JSON parsing error: {e}')
"
        
    - name: Run sync validation
      run: |
        python test_setup.py
        
    - name: Run Shopify sync
      run: |
        python shopify_sheets_sync.py
        
    - name: Show sync status
      run: |
        python sync_manager.py status
        
    - name: Check for errors
      run: |
        python sync_manager.py errors
        
    - name: Upload logs as artifacts (on failure)
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: sync-logs
        path: |
          shopify_sync.log
          shopify_sync.db
        retention-days: 7